### PR TITLE
Skip deployment in Maven if no deployer is specified.

### PR DESCRIPTION
**Pull request by tynutsu**
- [ ] All [tests](https://github.com/jfrog/artifactory-azure-devops-extension#testing) passed. If this feature is not already covered by the tests, I added new tests.
- [ ] I used `npm run format` for formatting the code before submitting the pull request.
-----

### CODE REVIEW

**Comment by tynutsu** [comment]
Gradle task skips adding --server-id-deploy if no artifactoryDeployer is specified. Like on gradle task the artifactoryDeployerService is not required
Having the deployer optional, allows users to execute the install task (which mean install to local repo) as it should if they skip the deployment by not mentioning a service connection for deployment.

**Review by yahavi — CHANGES_REQUESTED** [review]
Thanks for this contribution, @tynutsu!
We want to merge your PR. I have one comment:
Our release automation updates the tasks versions automatically. Before merging your pull request, please remove the versions updates and leave only the relevant code.

FYI, there is an [issue](https://github.com/jfrog/jfrog-cli/issues/790) in the CLI which prevents running maven commands without deployer. I created this [PR](https://github.com/jfrog/jfrog-cli-core/pull/7) to overcome it. We will have to release JFrog CLI before releasing Artifactory Azure DevOps extension.

**Comment by tynutsu** [comment]
reverted manual version update as requested

**Comment by tynutsu** [comment]
I have updated the pr (accidentally closed it)

**Review by yahavi — APPROVED** [review]
LGTM

**Comment by RobiNino** [comment]
Hi @tynutsu ,
We would like to merge, but it looks like we had a problem with our CLA Assistant bot. 
We would really appreciate it if you could sign our [Contributor License Agreement](https://gist.github.com/jfrog-ecosystem/7d4fbeaac18edbd3cfc38831125acbb3) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.
   - - -
   ***I have read the CLA Document and I hereby sign the CLA***
   - - - 
Thanks again!

**Comment by tynutsu** [comment]
signed

**Comment by eyalbe4** [comment]
@tynutsu - 
I have to apologies for all the trouble. Migrating from the old system to the new one is more challenging than we expected.
If you can just read this [Contributor License Agreement](https://gist.github.com/jfrog-ecosystem/7d4fbeaac18edbd3cfc38831125acbb3) and add the below text as a comment in this issue, we'll merge and release.
**I have read the CLA Document and I hereby sign the CLA**

**Comment by tynutsu** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by tynutsu** [comment]
I have read the CLA Document and I hereby sign the CLA

recheckcla

**Comment by RobiNino** [comment]
Thanks again @tynutsu , sorry for the trouble.

**Pull request merged**
